name: "Agent"
run-name: "Agent"

on: 
   issues:
     types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      contents: read   
      issues: write    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      # - name: "Search for Repository"
    
