name: "GitHub Actions Read Pull Request"
run-name: "itHub Actions Read Pull Request"

on:
   pull_request:
      types: [opened]

jobs:
  readPush:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      pull-requests: read
    steps: 
      - name: Check out pullrequest
        uses: actions/checkout@v4
    env:
      token: ${{ secrets.GITHUB_TOKEN }}
